version: build-{build}.{branch}
image: Visual Studio 2017

skip_branch_with_pr: true

environment:
  matrix:
    - version: 14
      variant: windowsservercore-ltsc2016
      vm: hotspot
      package: jdk
      runtype: test
    - version: 14
      variant: windowsservercore-ltsc2016
      vm: openj9
      package: jdk
      runtype: test
    - version: 14
      variant: windowsservercore-ltsc2016
      vm: hotspot
      package: jre
      runtype: test
    - version: 14
      variant: windowsservercore-ltsc2016
      vm: openj9
      package: jre
      runtype: test
    - version: 11
      variant: windowsservercore-ltsc2016
      vm: hotspot
      package: jdk
      runtype: test
    - version: 11
      variant: windowsservercore-ltsc2016
      vm: openj9
      package: jdk
      runtype: test
    - version: 11
      variant: windowsservercore-ltsc2016
      vm: hotspot
      package: jre
      runtype: test
    - version: 11
      variant: windowsservercore-ltsc2016
      vm: openj9
      package: jre
      runtype: test
    - version: 8
      variant: windowsservercore-ltsc2016
      vm: hotspot
      package: jdk
      runtype: test
    - version: 8
      variant: windowsservercore-ltsc2016
      vm: openj9
      package: jdk
      runtype: test
    - version: 8
      variant: windowsservercore-ltsc2016
      vm: hotspot
      package: jre
      runtype: test
    - version: 8
      variant: windowsservercore-ltsc2016
      vm: openj9
      package: jre
      runtype: test

build_script:
  - cmd: bash build_latest.sh %version% %vm% %package% %runtype%
