os: linux

language: bash
services: docker

env:
  matrix:
    - VERSION=14 VM=hotspot PACKAGE=jdk RUNTYPE=test
    - VERSION=14 VM=openj9 PACKAGE=jdk RUNTYPE=test
    - VERSION=14 VM=hotspot PACKAGE=jre RUNTYPE=test
    - VERSION=14 VM=openj9 PACKAGE=jre RUNTYPE=test
    - VERSION=11 VM=hotspot PACKAGE=jdk RUNTYPE=test
    - VERSION=11 VM=openj9 PACKAGE=jdk RUNTYPE=test
    - VERSION=11 VM=hotspot PACKAGE=jre RUNTYPE=test
    - VERSION=11 VM=openj9 PACKAGE=jre RUNTYPE=test
    - VERSION=8 VM=hotspot PACKAGE=jdk RUNTYPE=test
    - VERSION=8 VM=openj9 PACKAGE=jdk RUNTYPE=test
    - VERSION=8 VM=hotspot PACKAGE=jre RUNTYPE=test
    - VERSION=8 VM=openj9 PACKAGE=jre RUNTYPE=test

script: bash build_latest.sh $VERSION $VM $PACKAGE $RUNTYPE

stages:
  - linter
  - test

jobs:
  include:
    - stage: linter
      script: ./linter.sh
